# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfIhXjH4sGwLhSXrBwQus6NZ04EgZ66_
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):

    sample_rate, data = wavfile.read(wav_file)


    if len(data.shape) > 1:
        data = data[:, 0]

    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)
    plt.ylim(0, sample_rate / 2)
    plt.grid(True)
    plt.show()

wav_file_path = 'wav_file_path.wav'
generate_spectrogram(wav_file_path)

!pip install gtts
from gtts import gTTS
import os

text = "In its second week, 'Hello' stayed at number one on the US Billboard Hot 100, selling another 635,000 digital copies marking the third-best digital sales week and the highest for a non-debut week. "Hello" also held atop Streaming Songs with 47.4 million US streams, down 23 percent from 61.6 million in its first week, the track also stayed atop the On-Demand Songs with 18.1 million streams. On the Radio Songs chart,  moved from 9 to 6, up by 46% to 106 million all-format audience impressions, thus becoming the top Airplay Gainer on the Hot 100. "
language = 'en'
tts = gTTS(text=text, lang=language, slow=False)

audio_file = "output.mp3"
tts.save(audio_file)

from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os

text = "BEKZOD AKA BIILA"

language = 'en'
tts = gTTS(text=text, lang=language, slow=False)


audio_file = "output.mp3"
tts.save(audio_file)


from IPython.display import Audio
Audio(audio_file)